### PR TITLE
Database fluent api

### LINKED ISSUE #4: DB Fluent API
Create DB context, what included model creating by fluent api. Provide migration history

### PR DESCRIPTION
**Pull request by vlod11**
I want to resolve #4 by this pull request

### CODE REVIEW

**Comment by vlod11** [comment]
I want to resolve #4 by this pull request

**Review by vanmxpx — CHANGES_REQUESTED** [review]
Refactor code

**Review by vanmxpx — APPROVED** [review]

**Review by vanmxpx — CHANGES_REQUESTED** [review]
Refactor code

**Review by vanmxpx — APPROVED** [review]

**Comment by vanmxpx** [comment]
closed #4

**Pull request merged**
